[package]
name = "deps-gen"
version = "0.0.0"
edition = "2021"

[dependencies]
handlebars = { version = "5.1.0" }
serde = { version = "1.0.196", features = ["derive"] }
cargo_metadata = { version = "0.18.1" }
