[package]
name = "deps-gen"
version = "0.0.0"
edition = "2021"

[dependencies]
cargo-lock = { version = "9.0.0" }
handlebars = { version = "5.1.0" }
serde = { version = "1.0.196", features = ["derive"] }
